### PR TITLE
Cartable landing page

### PR DESCRIPTION
**Pull request by tech3371**

### CODE REVIEW

**Comment by kernelmethod** [comment]
Could you resize your logo to 360 x 260? Right now it's 320 x 140. Thanks!

**Comment by tech3371** [comment]
fixed size.

**Comment by kernelmethod** [comment]
Ah -- it should be 360 x **260**, not 360 x **360** (which is what you changed it to). Would you mind modifying it one more time? We just want to make sure the thumbnails for everybody's site are the same.

**Comment by tech3371** [comment]
sorry about that.

**Pull request merged**
